# ========================================
# CONFIGURACIÓN PRINCIPAL DE LA APLICACIÓN
# ========================================

# Perfil para debuguear
spring.profiles.active=local
# Importar todas las configuraciones modulares
spring.profiles.include=common,database,email,logging,security