# Configuración de JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=864000000

# Configuración del Client Secret
app.client.secret-header-name=X-Client-Secret
app.client.secret-value=${CLIENT_SECRET}

# Configuración de CORS para desarrollo
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*